version: '3.7'
services:
  idsvr:
    image: curity.azurecr.io/curity/idsvr:latest
    container_name: idsvr
    ports:
    - "6749:6749"
    - "8443:8443"
    environment:
      PASSWORD: Passw0rd1! ##admin user password
      # LOGGING_LEVEL: DEBUG
    networks:
      curity:
        aliases:
          - 'opa-kong-tutorial-idsvr'
  kong:
    build: ./kong-image
    container_name: kong
    volumes:
      - ./kong-image/kong.yml:/usr/local/kong/declarative/kong.yml
    ports:
     - "8000:8000"
     - "8001:8001"
     - "8442:8443"
     - "8444:8444"
    environment:
     - KONG_DATABASE=off
     - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
     - KONG_PLUGINS=bundled,phantom-token,opa
    #  - KONG_LOG_LEVEL=debug
     - KONG_PROXY_ACCESS_LOG=/dev/stdout
     - KONG_ADMIN_ACCESS_LOG=/dev/stdout
     - KONG_PROXY_ERROR_LOG=/dev/stderr
     - KONG_ADMIN_ERROR_LOG=/dev/stderr
     - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl
     - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    networks:
      curity:
        aliases:
          - 'opa-kong-tutorial-kong'
  api:
    build: ./api
    ports: 
      - "8080:8080"
    container_name: api
    hostname: api
    volumes: 
      - ./api/server/records.json:/app/records.json
    networks:
      curity:
        aliases:
          - 'opa-kong-tutorial-api'
  opa:
    image: openpolicyagent/opa:0.43.0
    container_name: opa

    ports:
    - "8181:8181"
    volumes:
      - ./opa/policies/:/records
    command: "run --server --addr :8181 /records"
    # command: "run --server --addr :8181 --log-level debug /records"
    networks:
      curity:
        aliases:
          - 'opa-kong-tutorial-opa'
networks:
  default:
    external:
      name: 'curity'
  curity:
    external: true
